// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemindersManagement.API.Infrastructure.Data;

#nullable disable

namespace RemindersManagement.API.Infrastructure.Migrations
{
    [DbContext(typeof(RemindersDbContext))]
    partial class RemindersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("RemindersManagement.API.Domain.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Reminders", "reminders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89fe00ac-d931-4227-8649-b83f7333aba7"),
                            Description = "Learning Microservices",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("73163bee-9059-4838-a535-6d46995da7fd"),
                            Description = "Writing Blog",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("338dcd20-bcc6-432e-b26d-fcc3d4d07bfe"),
                            Description = "Presentation prepare",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
