// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemindersManagement.API.Infrastructure.Data;

#nullable disable

namespace RemindersManagement.API.Infrastructure.Migrations
{
    [DbContext(typeof(RemindersDbContext))]
    partial class RemindersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("RemindersManagement.API.Domain.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Reminders", "reminders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a56dbde-f01e-4a34-89ec-b85f585d368a"),
                            Description = "Learning Microservices",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ce811a26-5562-4d02-8fe1-a3ed174e72c0"),
                            Description = "Writing Blog",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7b8a2f7f-9d99-4664-922b-bd7783770e2a"),
                            Description = "Presentation prepare",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
